name: Build and test

on:
  push:
    branches:
      - master
      - development
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install depencencies
      run: npm ci
    - name: Build library
      run: npm run build
    - name: Run tests
      run: npm run test
    - name: Send data to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
