
# name: Generate docs and push to Github pages
# on:
#   push:
#     branches:
#       - master
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v1

#     - name: Build
#       run: |
#         npm install
#         npm run docs
#         touch ./docs-automatic/.nojekyll

#     - name: Deploy
#       uses: JamesIves/github-pages-deploy-action@releases/v3
#       with:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         BRANCH: gh-pages
#         FOLDER: docs-automatic
